version: "3.9"

networks:
  metrics-net:
    driver: bridge

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./configs/prometheus:/etc/prometheus:Z
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - metrics-net
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_LOG_MODE=console
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./configs/grafana/provisioning:/etc/grafana/provisioning:Z
    depends_on:
      - prometheus
      - loki
    networks:
      - metrics-net
    restart: unless-stopped

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./configs/loki:/etc/loki:Z
    command: -config.file=/etc/loki/loki-config.yaml
    networks:
      - metrics-net
    restart: unless-stopped

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /tmp/logs:/tmp/logs:Z
      - ./configs/promtail:/etc/promtail:Z
    command: -config.file=/etc/promtail/promtail-config.yaml
    depends_on:
      - loki
    networks:
      - metrics-net
    restart: unless-stopped

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    ports:
      - "4317:4317"  # OTLP gRPC
      - "4318:4318"  # OTLP HTTP
      - "9464:9464"  # Prometheus metrics
    volumes:
      - ./configs/otel-collector:/etc/otel-collector:Z
    command: ["--config=/etc/otel-collector/otel-collector-config.yaml"]
    depends_on:
      - loki
    networks:
      - metrics-net
    restart: unless-stopped
