server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: livetran-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: livetran
          __path__: /log/livetran.log    # updated path inside container
    pipeline_stages:
      - json:
          expressions:
            level: level
            msg: msg
            time: time
